# Generated by Django 2.0.1 on 2018-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180320_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standardTime',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
