# Generated by Django 2.0.1 on 2018-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180320_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standardTime',
            field=models.TimeField(null=True),
        ),
    ]
