# Generated by Django 2.0.1 on 2018-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180320_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standardTime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
