# Generated by Django 2.0.1 on 2018-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180320_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
