# Generated by Django 2.0.1 on 2018-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180404_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
