# Generated by Django 2.0.1 on 2018-04-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180404_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hasReport',
            field=models.BooleanField(default=False),
        ),
    ]
