# Generated by Django 2.0.1 on 2018-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180509_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskType',
            field=models.IntegerField(max_length=100),
        ),
    ]
