# Generated by Django 2.1.2 on 2018-11-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180511_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
